<?php
  $userName = "Andres Pihl";
  $fullTimeNow = date ("d.m.Y H:i:s");
  $hourNow = date ("H");
  $partOfDay = "hägune aeg.";
  if($hourNow < 8){
	$partOfDay = "hommik.";
  }
?>
<!DOCTYPE html>
<html>
<html lang="la">
<head>
  <meta charset="utf-8">
  <title>
  <?php
    echo $userName;
  ?>
  programmerib veebi</title>
  <style type="text/css">
			body {
				font-family: comic-sans;
				width: 1080px;
				margin: 20px auto;
			}
            h1 {
                margin-top: 60px;
            }
		</style>
</head>

<body>
<div align="center"><a href="javascript:var%20i,s,ss=['http://kathack.com/js/kh.js','http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js'];for(i=0;i!=ss.length;i++){s=document.createElement('script');s.src=ss[i];document.body.appendChild(s);}void(0);"title="Katamari!">
<?php
  Echo "<H1>".$userName." programmerib veebi</a></H1></div>";
?>
<div align="justify"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce purus justo, ullamcorper sit amet efficitur id, luctus ac neque. Sed facilisis et quam quis sodales. Phasellus ut lacus quam. Fusce non ullamcorper justo. Proin ut lectus ultricies, pellentesque metus quis, mattis purus. Donec faucibus consectetur dictum. Vestibulum ornare orci nec neque mollis porta. Cras et augue hendrerit neque tincidunt rhoncus.</p>
<p>Cras faucibus porttitor blandit. Suspendisse fermentum nibh in diam pharetra fringilla. Nunc tempor ex in odio malesuada congue. Vestibulum lacinia ipsum mi, in pulvinar enim convallis et. Praesent nec est sed magna pharetra pretium id sollicitudin augue. Curabitur vel sem sed tortor posuere dapibus at et orci. Aliquam vulputate varius neque. Donec quis enim imperdiet, maximus nisi eget, eleifend ipsum.</p>
<p>Phasellus nunc lacus, tincidunt ac justo et, pulvinar dignissim nisi. Mauris non aliquam tellus. Praesent feugiat condimentum lorem, a aliquet justo facilisis sit amet. Mauris mattis cursus lobortis. Suspendisse sollicitudin scelerisque nunc, iaculis convallis risus aliquet finibus. Sed pharetra odio eget vulputate dapibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam pharetra velit quis augue pellentesque dignissim. Mauris pharetra metus vel metus convallis euismod. Vestibulum ac gravida orci, id placerat urna. Nam pretium massa eget turpis consequat, eget consectetur sem consequat. Sed vitae enim in purus scelerisque pulvinar. Vestibulum venenatis ex a ante vestibulum vulputate bibendum at libero. Suspendisse in blandit libero, nec gravida libero. Duis egestas ultrices mi id gravida. Nam non tincidunt diam.</p>
<p>Fusce eget nunc placerat, feugiat purus sed, blandit lorem. Duis sit amet tincidunt ipsum. Praesent et aliquet purus, eget sagittis urna. Mauris venenatis malesuada placerat. Integer quis facilisis nibh, non dapibus nibh. Duis porta, orci et posuere convallis, eros quam eleifend mauris, sed vulputate lacus lectus id lorem. Mauris auctor sapien eu libero aliquet bibendum. Fusce at rutrum orci. Etiam mollis tincidunt sapien ac ullamcorper. Vestibulum in diam porttitor, porta turpis sit amet, pharetra est. Vestibulum pharetra, lacus iaculis efficitur feugiat, lectus dui dignissim mi, a cursus quam urna maximus sem. In ac nisi in felis sodales scelerisque.</p>
<p>Cras sed elementum nunc. Integer hendrerit at orci ac faucibus. Nunc tincidunt vestibulum eros ac rhoncus. Phasellus aliquam eu tortor in congue. In leo lacus, sagittis et dolor at, pharetra pharetra nisl. Sed fermentum laoreet placerat. In sed scelerisque nisl. Integer dapibus lectus mauris, in sollicitudin nulla tempus eget. Quisque bibendum nisi et dolor sodales sagittis. In posuere lectus imperdiet felis sollicitudin, dapibus sodales mauris bibendum. Curabitur mattis ac arcu volutpat blandit. Maecenas ultricies tellus non metus porta, vitae aliquam sem consectetur.</p>
<p>Praesent blandit nisl laoreet augue condimentum, quis rhoncus sem pharetra. Maecenas lobortis rutrum dui ac sodales. Integer dignissim lectus non arcu fermentum, sed consectetur nunc vulputate. Quisque orci ipsum, malesuada a mollis nec, tincidunt vitae enim. Donec interdum tincidunt magna vel dapibus. Pellentesque non enim ultricies, ultricies dui a, tempus neque. Aenean sollicitudin eros in blandit luctus. Aenean massa leo, scelerisque vel sagittis ac, molestie ut ex. Ut rutrum lacus eget imperdiet interdum. Mauris sed arcu nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi rutrum dapibus massa nec condimentum.</p>
<p>Sed eget urna ut nulla aliquet rhoncus. Proin nec ex euismod, tincidunt erat at, lacinia mi. Nullam non ante eget nunc dictum commodo nec sed magna. Donec vel vulputate sapien, quis viverra lectus. Donec neque erat, ullamcorper sit amet tincidunt tincidunt, vestibulum sed diam. In eget risus vitae metus cursus commodo elementum a eros. Morbi lectus ante, aliquam ut tristique porta, consequat eu diam. Curabitur sit amet rutrum sapien. Donec placerat sapien purus, et porta ligula mattis non. Aliquam tincidunt et massa ut fringilla. Quisque vitae velit libero. Sed ante eros, blandit nec malesuada et, congue quis elit. Aliquam ultrices, libero sed laoreet euismod, enim lorem rutrum orci, ac suscipit erat augue fringilla est. Vestibulum justo lorem, condimentum et metus sit amet, interdum vehicula odio.</p>
<p>Sed sit amet turpis consequat, sollicitudin ligula at, feugiat tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vehicula efficitur libero, sed feugiat magna sagittis et. Vivamus orci tortor, cursus sed dolor et, lacinia iaculis enim. Nulla facilisi. Aenean tellus tellus, sodales sed tempor et, euismod et tellus. Maecenas risus velit, faucibus quis nunc non, vehicula malesuada mauris.</p>
<p>Nam tempor justo nec velit sollicitudin, non egestas libero euismod. Nunc in mauris diam. Phasellus eget massa eros. Etiam eget cursus massa, eu facilisis elit. Donec tristique metus vel suscipit congue. Morbi pharetra pharetra sapien sed commodo. Donec tristique rutrum consequat. Mauris tincidunt eget purus id consequat. Phasellus id iaculis mi, eu accumsan quam.</p>
<p>Aenean interdum tortor nibh, ac molestie orci finibus a. Sed tincidunt augue vitae quam rutrum, eu eleifend magna hendrerit. Donec magna mauris, dapibus ut feugiat venenatis, pretium eget turpis. Donec dignissim nibh augue, quis tincidunt nisl imperdiet id. Curabitur malesuada tortor sit amet nisl feugiat ullamcorper. Donec velit enim, maximus sit amet sapien nec, vestibulum efficitur velit. Sed feugiat, massa vitae posuere congue, magna mi ultrices dui, in porta urna ligula quis arcu. Curabitur facilisis egestas risus, sit amet venenatis mi posuere non. Curabitur accumsan ante sapien, nec laoreet diam interdum ac. Fusce in mattis lectus. Donec tempor risus nec facilisis hendrerit.</p>
<p>Morbi id consectetur nunc. Curabitur gravida est eget ante pulvinar consectetur. Quisque quis viverra est, non ultricies neque. Donec vel ullamcorper nisl, nec aliquet libero. Phasellus ornare ut mi vel egestas. Morbi cursus sagittis leo, a vehicula tellus efficitur eu. Donec sed eros ac sem vulputate auctor in vitae urna. Nunc varius turpis eu est malesuada porttitor. Ut sapien turpis, pretium ac nisl vitae, sollicitudin auctor nibh. Nunc feugiat felis at augue interdum eleifend. Sed tristique fringilla metus, non placerat lacus semper sit amet. Mauris sit amet consequat nibh. Donec at viverra metus, ut porta nisi. Curabitur sollicitudin sed velit nec tincidunt. Nullam aliquam, enim a cursus mollis, justo libero elementum nibh, sed dictum magna nulla non urna.</p>
<p>Cras ut sapien porttitor nisi pretium tempor. Mauris ut auctor lorem. Phasellus et vulputate dolor. Aenean varius et tortor at sagittis. Quisque at ornare ex. In efficitur faucibus sem id volutpat. Ut in velit consequat, convallis elit id, rutrum lacus. Donec id hendrerit purus. Nullam interdum tempor convallis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel velit in nunc porttitor rutrum. Fusce semper elementum lorem, vitae auctor risus lacinia eget.</p>
<p>Vestibulum vel aliquet dolor. Aenean vehicula lorem est, ut faucibus arcu efficitur non. Donec vel leo eget mauris faucibus commodo ac ut quam. Phasellus dignissim orci felis, a lacinia purus pharetra ornare. Duis ultrices quam ac tincidunt accumsan. Sed mollis libero consectetur elit iaculis aliquam. Curabitur dapibus sapien sit amet enim imperdiet tempor.</p>
<p>Cras luctus a quam a facilisis. Nulla nisl odio, porttitor sit amet consequat sollicitudin, pulvinar nec lectus. Mauris quis auctor velit. Sed a feugiat nisl. Cras tempor nisi at erat tempus, non iaculis mauris lacinia. Nullam egestas mauris et ante fermentum elementum. Nam elementum eleifend dignissim. Vivamus ut erat a magna congue finibus. Aenean luctus at purus ac vehicula. Proin ornare risus quis ipsum faucibus pharetra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi et mattis enim. Ut tincidunt, urna nec viverra convallis, orci massa imperdiet nibh, at dignissim ipsum risus eu metus. Integer semper dui in ultricies congue.</p>
<p>Nulla sed ex interdum nisl porttitor lacinia. Curabitur mi turpis, consequat sit amet orci quis, vestibulum varius leo. Etiam sagittis sagittis sapien, at varius dolor congue nec. Nulla non tempor nulla. Integer dapibus nibh sit amet blandit hendrerit. Nunc pharetra lacinia neque vel consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque tincidunt sodales mollis. Sed ultricies sapien nec lorem ullamcorper, ac tincidunt velit suscipit. Proin bibendum justo quam, eu feugiat arcu dictum quis. Donec a turpis eget mauris cursus vulputate nec in elit. Cras eget ipsum efficitur, ultrices neque a, vestibulum neque. Vivamus id nunc auctor, rutrum urna at, vehicula massa.</p>
<p>Maecenas in orci et lorem pulvinar feugiat. Donec dignissim quam sem, non malesuada dolor fermentum ut. Aliquam urna sapien, interdum ac dignissim a, vulputate sed justo. Proin dignissim accumsan eleifend. Nam faucibus odio a dui luctus, et iaculis magna consequat. Phasellus odio felis, maximus eu magna et, molestie volutpat nulla. Donec iaculis ut ante vel hendrerit. Praesent orci eros, scelerisque quis sapien at, pulvinar interdum odio. In rutrum augue quis eros fermentum, vitae euismod felis euismod. Aenean augue neque, bibendum quis nisi eget, commodo ornare arcu. Phasellus lacinia turpis vel mauris sollicitudin, eu pretium neque aliquam. Cras cursus sem consequat justo commodo, ut condimentum tortor venenatis. Nam egestas erat eu dui accumsan, eget lobortis sapien dapibus. Suspendisse ac massa aliquam augue rutrum vestibulum id vitae dolor. Nam ac lorem ac neque commodo dignissim.</p>
<p>In eget lorem tincidunt, finibus sem ut, aliquam nibh. Pellentesque a efficitur tortor. Fusce in sollicitudin quam. Vestibulum odio lacus, vulputate quis diam et, semper efficitur ipsum. Morbi malesuada libero semper nisi tempus mollis. Fusce posuere vestibulum urna, sit amet tristique urna feugiat nec. Nam imperdiet id tellus et volutpat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent augue tellus, fermentum a porttitor a, tincidunt vitae justo. Sed ac eros sit amet metus bibendum sodales. Mauris sagittis nunc vel tellus malesuada scelerisque.</p>
<p>Nullam dapibus justo quis accumsan aliquet. Aenean nec est urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam luctus varius eros sed iaculis. Phasellus faucibus orci vel tincidunt vulputate. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec vestibulum erat at rhoncus consectetur. Integer non magna elit. Donec volutpat lectus vestibulum, tempus metus non, scelerisque urna. Praesent eleifend eleifend pulvinar. Sed ac consequat turpis. Vestibulum sit amet leo turpis. Nunc magna urna, bibendum vitae dui eu, posuere finibus felis. Vivamus non ullamcorper risus.</p>
<p>Nam aliquet, arcu quis ullamcorper aliquet, elit nisl pharetra turpis, a auctor turpis ante id ante. Aliquam id augue eu est congue venenatis. Mauris vehicula laoreet enim, a luctus ante gravida sed. Donec a condimentum massa. Sed eget quam velit. Proin tincidunt mollis nibh, nec ullamcorper libero dictum a. Etiam condimentum elit lacus, quis ullamcorper massa interdum sed. Ut pretium turpis ut metus dapibus tempor. Pellentesque nec blandit massa. Mauris orci risus, eleifend vitae neque nec, elementum scelerisque risus. Pellentesque sed porttitor urna. Suspendisse non sapien nec velit elementum posuere vitae nec turpis. Mauris convallis odio eu condimentum mollis. Duis tellus mi, dictum non placerat vitae, dapibus id enim. Duis imperdiet volutpat felis, sit amet imperdiet lorem fringilla a.</p>
<p>Suspendisse lobortis a dolor pharetra commodo. Mauris pharetra mattis metus at condimentum. Proin eget arcu ac ex posuere interdum efficitur eu diam. Maecenas eros arcu, venenatis id est eu, mollis interdum purus. Cras mollis semper erat, nec sagittis eros rhoncus sit amet. Sed quis arcu tincidunt, ornare erat id, aliquet lacus. Ut varius scelerisque mi quis lobortis. Phasellus id dignissim felis, ac malesuada augue. In vehicula finibus consequat. Curabitur in consectetur sapien, sed posuere lacus. Mauris justo turpis, vulputate vel volutpat id, lobortis eu augue. Nam lorem diam, suscipit vel felis sit amet, euismod faucibus ipsum.</p>
</div>
<hr><div align="Right"><?php
  echo "<p>Leht avati ".$fullTimeNow.", ".$partOfDay."</p>";
?></div>
</body>
</html>